services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - preferences
      - reviews
      - users

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    depends_on:
      - rabbitmq
      - postgres-db-users

  preferences:
    build:
      context: .
      dockerfile: ./apps/preferences/Dockerfile
      target: development
    command: npm run start:dev preferences
    env_file:
      - ./apps/preferences/.env
    depends_on:
      - rabbitmq
      - mongo-db-preferences

  reviews:
    build:
      context: .
      dockerfile: ./apps/reviews/Dockerfile
      target: development
    command: npm run start:dev reviews
    env_file:
      - ./apps/reviews/.env
    depends_on:
      - rabbitmq
      - mongo-db-reviews

  mongo-db-reviews:
    image: mongo
    ports:
      - '27018:27017'
    restart: always
    volumes:
      - ./data:/data/mongo-db-reviews
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-db-preferences:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./data:/data/mongo-db-movies
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres-db-users:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres-db-users
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-micro-users

  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq


