services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - preferences
      - reviews
      - users
    ports:
      - '3000:3000'

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    depends_on:
      - rabbitmq
      - postgres-db-users
    ports:
      - '3003:3000'

  preferences:
    build:
      context: .
      dockerfile: ./apps/preferences/Dockerfile
      target: development
    command: npm run start:dev preferences
    env_file:
      - ./apps/preferences/.env
    depends_on:
      - rabbitmq
      - mongo-db-preferences
    ports:
      - '3002:3000'
  news-feed:
    build:
      context: .
      dockerfile: apps/news-feed/Dockerfile
      target: development
    command: npm run start:dev news-feed
    env_file:
      - apps/news-feed/.env
    depends_on:
      - rabbitmq
      - mongo-db-news-feed
    ports:
      - '3001:3000'

  mongo-db-news-feed:
    image: mongo
    ports:
      - '27018:27017'
    restart: always
    volumes:
      - ./data:/data/mongo-db-news-feed
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-db-preferences:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./data:/data/mongo-db-preferences
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgres-db-users:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres-db-users
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-micro-users

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - ./rabbitmq_data:/var/lib/rabbitmq
